apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apps-sa-admin-binding
subjects:
- kind: User
  name: system:serviceaccount:apps:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

